language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get install liblapack-dev python-scipy libblas-dev
install: 
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install git+https://github.com/Theano/Theano.git
  - pip install pandas
  - python setup.py build_ext --inplace
script: 
  - nosetests -s tests/ 
